"use client";

import dynamic from "next/dynamic";
import { useMemo, useState } from "react";
import { motion as Motion } from "framer-motion";
import {
  Activity,
  BrainCircuit,
  Bug,
  Camera,
  Gauge,
  ListChecks,
  Network,
  TerminalSquare,
  FileDown,
  ChevronRight
} from "lucide-react";
import { AnimatedSection } from "@/components/AnimatedSection";
import { FeatureCard } from "@/components/FeatureCard";
import { Footer } from "@/components/Footer";
import { Hero } from "@/components/Hero";
import { Navbar } from "@/components/Navbar";
import { PricingCard } from "@/components/PricingCard";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Skeleton } from "@/components/ui/skeleton";

const LivePreviewSection = dynamic(
  () => import("@/components/sections/LivePreviewSection").then((mod) => mod.LivePreviewSection),
  {
    loading: () => (
      <div className="mx-auto w-full max-w-6xl px-4 py-20 sm:px-6">
        <Skeleton className="h-12 w-72" />
        <Skeleton className="mt-6 h-64 w-full" />
      </div>
    )
  }
);

const featureCards = [
  {
    title: "Automated Web Testing",
    description: "Run instant, repeatable checks across key pages and flows.",
    icon: Activity
  },
  {
    title: "Console & Network Error Tracking",
    description: "Capture failed calls, exceptions, and browser-level diagnostics.",
    icon: Network
  },
  {
    title: "AI Root Cause Analysis",
    description: "Get likely root causes and practical fixes generated by AI.",
    icon: BrainCircuit
  },
  {
    title: "Screenshot Capture",
    description: "Store visual evidence with every report for quick triage.",
    icon: Camera
  },
  {
    title: "Performance Metrics",
    description: "Track response timings and page-load behaviors automatically.",
    icon: Gauge
  },
  {
    title: "Exportable Reports",
    description: "Share structured bug reports with dev and product teams.",
    icon: FileDown
  }
];

export default function Home() {
  const [yearly, setYearly] = useState(false);

  const pricing = useMemo(
    () => [
      {
        tier: "Free",
        price: yearly ? "$0" : "$0",
        description: "For solo developers validating personal projects.",
        features: ["20 tests/month", "Basic error detection", "Community support"]
      },
      {
        tier: "Pro",
        price: yearly ? "$39/mo" : "$49/mo",
        description: "For startups shipping fast and fixing issues early.",
        features: ["Unlimited tests", "AI bug analysis", "Priority processing", "Exportable reports"],
        highlighted: true
      },
      {
        tier: "Team",
        price: yearly ? "$99/mo" : "$129/mo",
        description: "For product teams requiring collaboration and scale.",
        features: ["Role-based access", "Team dashboards", "SLA support", "Audit logs"]
      }
    ],
    [yearly]
  );

  return (
    <div className="relative min-h-screen overflow-x-hidden bg-slate-50 text-slate-900 dark:bg-slate-950 dark:text-slate-100">
      <div className="absolute inset-0 -z-20 hero-gradient" />
      <Motion.div className="blob -left-20 top-24 h-64 w-64 bg-indigo-500" animate={{ x: [0, 12, 0], y: [0, -12, 0] }} transition={{ duration: 8, repeat: Infinity }} />
      <Motion.div className="blob right-0 top-48 h-72 w-72 bg-cyan-500" animate={{ x: [0, -12, 0], y: [0, 10, 0] }} transition={{ duration: 9, repeat: Infinity }} />
      <div className="absolute inset-0 -z-10 bg-grid opacity-45" />

      <Navbar />
      <main>
        <Hero />

        <AnimatedSection className="px-4 py-14 sm:px-6">
          <div className="mx-auto w-full max-w-6xl">
            <p className="text-xs uppercase tracking-[0.22em] text-indigo-600 dark:text-indigo-300">Built for Developers</p>
            <div className="mt-4 flex flex-wrap gap-3">
              {[
                "Console Error Detection",
                "Performance Insights",
                "AI Bug Analysis"
              ].map((badge) => (
                <Badge key={badge} className="cursor-default border-indigo-300/50 bg-indigo-500/10 text-indigo-700 hover:scale-[1.02] hover:border-indigo-400 dark:border-white/20 dark:bg-white/10 dark:text-slate-100 dark:hover:bg-indigo-500/20">
                  {badge}
                </Badge>
              ))}
            </div>
          </div>
        </AnimatedSection>

        <AnimatedSection id="features" className="px-4 py-20 sm:px-6">
          <div className="mx-auto w-full max-w-6xl">
            <div className="mb-8 space-y-3">
              <p className="text-xs uppercase tracking-[0.22em] text-indigo-600 dark:text-indigo-300">Features</p>
              <h2 className="text-3xl font-bold text-slate-900 sm:text-4xl dark:text-white">Everything Needed for Fast Bug Detection</h2>
            </div>

            <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">
              {featureCards.map((feature, index) => (
                <FeatureCard key={feature.title} title={feature.title} description={feature.description} icon={feature.icon} index={index} />
              ))}
            </div>
          </div>
        </AnimatedSection>

        <AnimatedSection id="how" className="px-4 py-20 sm:px-6">
          <div className="mx-auto w-full max-w-6xl">
            <p className="text-xs uppercase tracking-[0.22em] text-indigo-600 dark:text-indigo-300">How It Works</p>
            <h2 className="mt-3 text-3xl font-bold text-slate-900 sm:text-4xl dark:text-white">From URL to Actionable Report in 3 Steps</h2>

            <div className="mt-10 grid gap-4 md:grid-cols-3">
              {[
                { title: "Enter Your URL", icon: TerminalSquare },
                { title: "AI Scans & Analyzes", icon: Bug },
                { title: "Get Actionable Bug Reports", icon: ListChecks }
              ].map((step, index) => (
                <div key={step.title} className="relative rounded-2xl border border-slate-200/80 bg-white/60 p-5 backdrop-blur-xl dark:border-white/15 dark:bg-white/8">
                  <step.icon className="h-5 w-5 text-indigo-500 dark:text-indigo-300" />
                  <p className="mt-4 font-semibold text-slate-900 dark:text-white">Step {index + 1}</p>
                  <p className="mt-1 text-sm text-slate-600 dark:text-slate-300">{step.title}</p>
                  {index < 2 ? (
                    <Motion.div
                      className="absolute -right-5 top-1/2 hidden text-indigo-500 dark:text-indigo-300 md:block"
                      animate={{ x: [0, 6, 0] }}
                      transition={{ duration: 1.4, repeat: Infinity }}
                    >
                      <ChevronRight className="h-5 w-5" />
                    </Motion.div>
                  ) : null}
                </div>
              ))}
            </div>
          </div>
        </AnimatedSection>

        <LivePreviewSection />

        <AnimatedSection id="pricing" className="px-4 py-20 sm:px-6">
          <div className="mx-auto w-full max-w-6xl">
            <div className="mb-8 flex flex-wrap items-center justify-between gap-4">
              <div className="space-y-2">
                <p className="text-xs uppercase tracking-[0.22em] text-indigo-600 dark:text-indigo-300">Pricing</p>
                <h2 className="text-3xl font-bold text-slate-900 sm:text-4xl dark:text-white">Simple Plans for Every Stage</h2>
              </div>

              <button
                type="button"
                onClick={() => setYearly((prev) => !prev)}
                className="rounded-xl border border-slate-300 bg-white/60 px-4 py-2 text-sm text-slate-800 hover:bg-white dark:border-white/15 dark:bg-white/10 dark:text-slate-100 dark:hover:bg-white/20"
              >
                {yearly ? "Yearly Billing" : "Monthly Billing"}
              </button>
            </div>

            <div className="grid gap-4 lg:grid-cols-3">
              {pricing.map((plan) => (
                <PricingCard key={plan.tier} {...plan} />
              ))}
            </div>
          </div>
        </AnimatedSection>

        <AnimatedSection className="px-4 pb-20 pt-6 sm:px-6">
          <div className="mx-auto w-full max-w-6xl rounded-3xl border border-indigo-300/30 bg-gradient-to-r from-indigo-500/30 via-cyan-500/20 to-indigo-500/25 p-8 text-center backdrop-blur-2xl">
            <h2 className="text-3xl font-bold text-slate-900 sm:text-4xl dark:text-white">Ship Confidently. Test Smarter.</h2>
            <p className="mx-auto mt-3 max-w-2xl text-slate-700 dark:text-slate-200">
              Detect regressions earlier, resolve issues faster, and deliver better product quality with AutoForge AI.
            </p>
            <Button className="mt-6" size="lg">Get Started Now</Button>
          </div>
        </AnimatedSection>
      </main>

      <Footer />
    </div>
  );
}
